openapi: 3.0.2
servers:
  - url: /api/v1
    description: Version 1.
  - url: /api/v2
    description: Version 2.
  - url: /api/v3
    description: Version 3

info:
  version: 1.0.17
  title: Swagger SV MELDEPORTAL - OpenAPI 3.0
paths:
  /mandate/request:
    post:
      tags:
        - Mandate
      summary: Request Mandate for companies
      description: Request Mandate for companies
      operationId: requestMandate
      x-swagger-router-controller: MandateController
      responses:
        '201':
          description: Mandate Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mandate'
      security:
        - api_key: []
  /mandate/confirm/{companyNumber}:
    post:
      tags:
        - Mandate
      summary: Confirm of mandate of company
      description:  Confirm of mandate of company
      operationId: confirmMandate
      x-swagger-router-controller: MandateController
      parameters:
        - name: companyNumber
          in: path
          description: company number of mandate that needs to be grant access
          required: true
          schema:
            type: string
            example: 231828912
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantMandate'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /mandate/delete/{companyNumber}:
    post:
      tags:
        - Mandate
      summary: Delete Mandate of Company
      description: Delete Mandate of Company
      operationId: deleteMandate
      x-swagger-router-controller: MandateController
      parameters:
        - name: companyNumber
          in: path
          description: company number of mandate that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mandate Successfully was deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /mandate/revoke/{companyNumber}:
    post:
      tags:
        - Mandate
      summary: Revoke Mandate of Company
      description: Revoke Mandate of Company
      operationId: revokeMandate
      x-swagger-router-controller: MandateController
      parameters:
        - name: companyNumber
          in: path
          description: company number of mandate that needs to be revoked
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mandate Successfully was revoked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Mandate:
      properties:
        companyNumber:
          type: number
          description: The number of requested to access company
          example: 10013032
    GrantMandate:
      properties:
        activationCode:
          type: string
          description: The activation code of requested to access company
          example: GR3SV-BRS21-GHY23-BG5BE


      xml:
        name: mandate
      type: object
    ApiResponse:
      properties:
        response:
          type: object
          properties:
            statusCode:
              type: number
            messageType:
              type: string
            message:
              type: string
      xml:
        name: '##default'
      type: object
    ErrorResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            statusCode:
              type: number
            messageType:
              type: string
            message:
              type: string

