openapi: 3.0.2
servers:
  - url: /v3
info:
  description: |-
   SV MELDEPORTAL Server based on the OpenAPI 3.0 specification.
  version: 1.0.17
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: mandate
    description: Everything about Mandate
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: user
    description: Operations about Mandate
paths:
  /api/v1/mandate/request/apply:
    post:
      tags:
        - mandate
      summary: Request Mandate for companies
      description: Request Mandate for companies
      operationId: requestMandates
      x-swagger-router-controller: MandateController
      responses:
        '201':
          description: Mandate Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mandate'
      security:
        - api_key: []
  /api/v1/mandate/confirm/apply/{companyNumber}:
    post:
      tags:
        - mandate
      summary: Confirm of mandate of company
      description:  Confirm of mandate of company
      operationId: confirmMandate
      x-swagger-router-controller: MandateController
      parameters:
        - name: companyNumber
          in: path
          description: company number of mandate that needs to be grant access
          required: true
          schema:
            type: string
            example: 231828912
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantMandate'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/mandate/revoke/{companyNumber}:
    post:
      tags:
        - mandate
      summary: Revoke Mandate of Company
      description: Revoke Mandate of Company
      operationId: revokeMandate
      x-swagger-router-controller: MandateController
      parameters:
        - name: companyNumber
          in: path
          description: company number of mandate that needs to be revoked
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mandate Successfully was revoked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    Mandate:
      x-swagger-router-model: io.swagger.petstore.model.Mandate
      properties:
        companyNumber:
          type: string
          description: The number of requested to access company
          example: 82889062
    GrantMandate:
      x-swagger-router-model: io.swagger.petstore.model.Mandate
      properties:
        activationCode:
          type: string
          description: The activation code of requested to access company
          example: GR3SV-BRS21-GHY23-BG5BE

      xml:
        name: mandate
      type: object
    ApiResponse:
      properties:
        response:
          type: object
          properties:
            status:
              type: string
            message:
              type: string
      xml:
        name: '##default'
      type: object
    ErrorResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            status:
              type: number
              example: 400
            message:
              type: string
              example: Not Found

